### ISSUE TITLE
model option renaming

### ISSUE THREAD

**Issue by fserucas** [logreduce/logreduce-rust#33]
`logreduce-cli --model file_name`
Can the model option be renamed to **output-file** or to just **out**?

**Comment by TristanCacqueray** [comment]
The command line is currently using the same argument for output and input, the reasoning is that you can use:

```
$ logreduce --model my-model.clf train ...
$ logreduce --model my-model.clf url ...
```

I think this usage is simpler and I would prefer to avoid adding an extra option. Please let me know if #37 works better.
